developmentseed/tipg

docker-compose.yml
tests/routes/test_collections.py
tests/routes/test_non_geo.py
tipg/dbmodel.py
tipg/settings.py

Get min/max for datetime columns.
It's not entirely ideal because we need to make a request to the database for each datetime column, but without making a utility function similar to st_estimatedextent, I'm not sure we have much of an option.

get min/max for date columns

---

pyproject.toml

ref https://github.com/developmentseed/tipg/pull/15#issuecomment-1422876161

update sqlachemy version to avoid breaking changes

---

.pre-commit-config.yaml
tests/conftest.py
tests/routes/test_collections.py
tipg/db.py
tipg/dbmodel.py
tipg/factory.py
tipg/main.py
tipg/model.py
tipg/settings.py

This PR does:
- update mypy (couldn't get the all version run on my laptop 🙈)
- replace `TIPG_FUNCTIONS_DIRECTORY` by `TIPG_CUSTOM_SQL_DIRECTORY` 
- remove `TIPG_CUSTOM_SQL_DIRECTORY` from PostgresSettings
- refactor spatial and temporal extent (and fix tests)

update SQL Directory env and collection Extent

---

tipg/dbmodel.py

some geo related edits

---

tipg/db.py
tipg/sql/dbcatalog.sql

fix prop type

---

tipg/templates/collection.html
tipg/templates/header.html

remove mvt viz in collection page

---

tipg/factory.py
tipg/templates/map.html

add viewer

---

pyproject.toml

set maximum version for fastapi

---

tests/routes/test_tiles.py
tipg/dbmodel.py
tipg/dependencies.py
tipg/factory.py
tipg/settings.py

closes #38 
This PR split the TileSettings in two: TMSSettings and MVTSettings

split TMS and MVT Settings

---

docs/src/advanced/configuration.md
tipg/factory.py
tipg/main.py
tipg/settings.py

add option to add/remove viewer in tiles endpoints

---

docs/src/advanced/factories.md
docs/src/endpoints.md
tipg/dependencies.py
tipg/factory.py
tipg/templates/map.html

switch to z/x/y tile parameter

---

README.md
docker-compose.yml
docs/mkdocs.yml
docs/src/advanced/factories.md
docs/src/endpoints.md
tests/routes/test_tiles.py
tests/test_factories.py
tipg/dbmodel.py
tipg/factory.py
tipg/model.py
tipg/templates/map.html

This PR updates TileJSON spec to `3.0` and add a `/style.json` endpoint to return maplibre/mapbox StyleJSON document

add styleJSON and update TileJSON

---

docs/src/advanced/configuration.md

Add more docs for what is required to define custom functions.

Add docs for functions

---

tests/test_middleware.py
tipg/middleware.py

ref: https://www.starlette.io/middleware/#pure-asgi-middleware

rewrite middleware in pure asgi

---

CHANGES.md
docs/src/user_guide/endpoints.md
tests/routes/test_collections.py
tipg/factory.py

add `type` query parameter to filter collections based on their type (Function/Table)

add collection type filter

---

CHANGES.md
tests/conftest.py
tipg/main.py
tipg/middleware.py

enable passing a custom function in `CatalogUpdateMiddleware`
This will help to support more backends

allow custom function in middleware

---

CHANGES.md
pyproject.toml
tests/routes/test_collections.py
tests/routes/test_items.py
tests/routes/test_tiles.py
tests/test_schemas.py
tipg/factory.py

fix limit max bounds

---

CHANGES.md
tipg/dependencies.py
tipg/factory.py

ref https://github.com/developmentseed/tipg/pull/113#issuecomment-1693940669

change dependencies to callables

---

CHANGES.md
pyproject.toml

ref https://github.com/developmentseed/titiler/pull/746

limit fastapi upper version to avoid starlette breaking change

---

tests/routes/test_item.py
tipg/collections.py

This PR fix the issue found in #161 
- add `table_columns` in the `Collection` object (non-filtered properties)
- change `id_column` type from `string` to `Column` object (so we don't need `id_column_info` method)

forward table columns in collection object

---

CHANGES.md
pyproject.toml

ref https://github.com/tiangolo/fastapi/pull/11522

switch to fastapi-slim

---

CHANGES.md
tests/test_settings.py
tipg/settings.py

remove alias for tipg-schema in DatabaseSettings
