.pre-commit-config.yaml
docs/mkdocs.yml
docs/src/advanced/factories.md
tests/conftest.py
tests/test_factories.py
tipg/factory.py
tipg/main.py

closes #6 
This PR split the endpoint factory in two: `OGCFeaturesFactory` and `OGCTilesFactory` which should enable user to build either the tiles service or features service individually.
The main issue is for creating the OGC features `landing` and `conformances` endpoints. I've added two ways:
- within the `OGCFeaturesFactory`, by using the `full=True` option, this will add the `/` (landing) and `/conformance` endpoints but only referencing the features endpoint (no links to the Tiles endpoints).
```python
from tipg.factory import OGCFeaturesFactory
from fastapi import FastAPI
app = FastAPI(
openapi_url="/api",
docs_url="/api.html",
)
features = OGCFeaturesFactory(full=True)
app.include_router(features, tags=["OGC Features API"])
```
- in main.py, to have both tiles and features …

split OGC Features and Tiles endpoints factories

---

tests/conftest.py
tests/routes/test_collections.py
tests/routes/test_schemas.py
tests/test_schemas.py
tipg/db.py
tipg/dbmodel.py
tipg/logger.py
tipg/main.py
tipg/settings.py
tipg/sql/dbcatalog.sql

closes #44 
~~This PR tries to implement a solution based on https://github.com/developmentseed/tipg/issues/44#issuecomment-1486973429 but local tests shows that it doesn't work~~
```
docker-compose up database -d 
psql postgresql://username:password@0.0.0.0:5439/postgis -c "CREATE SCHEMA IF NOT EXISTS myschema; SET schema 'myschema'; DROP TABLE IF EXISTS myschema.countries CASCADE; CREATE TABLE myschema.countries AS SELECT * FROM public.countries; SELECT count(*) FROM myschema.countries;"
DATABASE_URL=postgresql://username:password@0.0.0.0:5439/postgis TIPG_DB_SCHEMAS='["myschema"]'  uvicorn tipg.main:app --port 8000 --reload
```
~~when `function_schemas` is set to `[]` using `TIPG_DB_FUNCTION_SCHEMAS='[]' then it works.~~

update search_path with user schemas

---

docs/src/advanced/configuration.md
tipg/dbmodel.py
tipg/factory.py
tipg/settings.py

closes #53 
This PR adds a new `Settings` with two variables:
- `default_features_limit`: Default LIMIT value (set to 10 by default)
- `max_features_per_query`: replace `max_features_per_tile` for `Collection.features` method

add setting to set Limit value

---

tests/conftest.py
tests/routes/test_collections.py
tests/test_main.py
tests/test_middleware.py
tipg/db.py
tipg/dbmodel.py
tipg/dependencies.py
tipg/errors.py
tipg/factory.py
tipg/logger.py
tipg/main.py
tipg/middleware.py
tipg/model.py
tipg/settings.py

This PR updates #68:
- move settings to the API settings 
- move state variable to the `Database` object (`last_updated`) 
- ~~add `lastUpdated` in the `/collections` response (NOT IN THE SPECIFICATION)~~
- remove the `refresh` catch in the middleware

Refactor #68: Database Catalog TTL

---

pyproject.toml
tipg/dependencies.py
tipg/factory.py

This PR update the `style` of dependencies type hints by using python `Annotated` type.
ref: 
- https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#additional-validation
- https://fastapi.tiangolo.com/tutorial/dependencies/classes-as-dependencies/?h=annotation#type-annotation-vs-depends
- https://fastapi.tiangolo.com/release-notes/#0951
This change is needed for https://github.com/developmentseed/tipg/issues/33
Sadly upgrading to FastAPI >0.94 means `Optional Path Parameter` is not supported anymore when using `Query/Path` parameter (see https://github.com/tiangolo/fastapi/discussions/9278, https://github.com/tiangolo/fastapi/pull/9670). This results in `less` description in OpenAPI for endpoints with optional `tileMatrixSetId` but I think for now this is not so bad.

switch to Annotation type hint

---

CHANGES.md
docs/src/advanced/customization.md
docs/src/user_guide/factories.md
tests/conftest.py
tests/routes/test_tiles.py
tipg/collections.py
tipg/database.py
tipg/dependencies.py
tipg/factory.py
tipg/main.py
tipg/middleware.py

This PR does:
- rename `tipg.db` -> `tipg.database`
- rename `tipg.dbmodel` -> `tipg.collections` 
- move `register_collection_catalog` in `tipg.collections`
- rename `tipg.collections.Database` -> `tipg.collections.Catalog`

refactor submodule names

---

docs/src/advanced/customization.md

example uses PostgresSettings, but imports DatabaseSettings, classes do not seem compatible so this change makes the import match what is used in the example

fix incorrect import in example

---

CHANGES.md
tests/routes/test_tiles.py
tipg/sql/dbcatalog.sql

We found a small bug where, if the geom is not 4326 it should transform to 4326 but instead the transform uses the SRID which the geom is already in.
Should [line 97](https://github.com/RemcoMeeuwissen/tipg/blob/main/tipg/sql/dbcatalog.sql#L97) also be changed? Because it's also going to use the geom native SRID rather than 4326.

Small fix to transform to 4326

---

CHANGES.md
tipg/templates/item.html
tipg/templates/items.html

- Previous version of popup content generation is vulnerable to [XSS attacks](https://owasp.org/www-community/attacks/xss/) due to crafting raw HTML from feature properties.
- Instead of generating the popup contents from string concatenation, generate from using document.`...` APIs instead
- This method of creating content, while more verbose, should not be vulnerable to XSS due to any feature content being added as innerText
Insert this table into the db:
```sql
CREATE TABLE xss (name varchar primary key, geom geometry, description varchar);
INSERT INTO xss VALUES ('XSS Test', 'POINT(0 0)', '<p onclick="alert(1)">click me!</p>');
```
Navigate to http://localhost:8000/collections/public.xss/items/XSS%20Test
On current main: notice that clicking on the popup, and then clicking on the …

generate popup contents without string concat.

---

CHANGES.md
tipg/dependencies.py
tipg/factory.py

add Catalog Dependency

---

CHANGES.md
tipg/settings.py

- set custom_sql_directory to default to None
- updated changelog
---
Without this, if no `custom_sql_directory` is specified, starting the default tipg.main:app will fail with a pydantic error

fix custom sql dir not optional

---

CHANGES.md
tipg/sql/dbcatalog.sql

closes #67 
This PR replace `string_to_table(...)` by `unnest(string_to_array(...))` to support older postgres 
> string_to_table() provides the set-based equivalent to [string_to_array()](https://pgpedia.info/s/string_to_array.html), and is functionally the same albeit somewhat faster than [unnest](https://pgpedia.info/u/unnest.html)(string_to_array())
From PG docs: https://pgpedia.info/s/string_to_table.html
Note: we could also use `regexp_split_to_table` https://pgpedia.info/r/regexp_split_to_table.html which seems to give the same result 🤷

use older function to support old Postgres

---

CHANGES.md
tipg/factory.py

This will allow user to create their own route

split route registration to allow endpoint overriding

---

docs/src/user_guide/configuration.md
tests/conftest.py
tests/routes/test_collections.py
tipg/collections.py
tipg/main.py
tipg/settings.py
tipg/sql/dbcatalog.sql

As discussed in #139, Calculating the extent of spatial/datetime columns can be slow enough that serverless deployments of `tipg` are not possible.
Skipping the extent calculations is one way to make application startup almost instantaneous! With this change, the user can set `TIPG_DB_SPATIAL_EXTENT=False` and `TIPG_DB_DATETIME_EXTENT=False` to skip these calculations.
I am not sure if passing these arguments all the way through to `pg_temp.tipg_properties` is the best way to accomplish this, but I got it working. If there is a cleaner way that you can think of please let me know!

make calculating spatial/datetime extents optional

---

tipg/factory.py
tipg/resources/response.py

Hey, we finally updated our version of tipg again and I discovered that my fix in pull request #89 was incomplete insofar that the web interface of tipg was also throwing the same error. So I extracted the orjson.dumps into a separate function so it can be used outside of the ORJSONResponse class as well
I think it doesn't require any new tests since the old tests for the decimal fix are still there and I assume the other responses are also already covered by tests. But if you want some stylistic changes or such just let me know :slightly_smiling_face:

Fix decimal error again

---

CHANGES.md
tests/routes/test_items.py
tipg/collections.py

fix `prev` offset

---

CHANGES.md
tipg/dependencies.py
tipg/factory.py
tipg/templates/collections.html

fix collection prev and other links

---

CHANGES.md
tests/conftest.py
tests/routes/test_item.py
tipg/collections.py
tipg/settings.py

attempt to closes https://github.com/developmentseed/tipg/discussions/158
While I think this PR `fixes` the original issue, when I added tests I found a `bug`. If we don't include the `id_column` in the properties then the code fails when it tries to retrieve the `id_column_info` (because it's not in the properties list)

parse sub-model for table_settings

---

tipg/main.py

- We added the `spatial_extent` and `datetime_extent` parameters to `register_collection_catalog` but they were only getting used in one of the calls to the function. After deploying `tipg` again on a database with some really large tables with spatial and temporal columns I realized that the extent calculations were still getting run but not at application startup!
- pass the `spatial_extent` and `datetime_extent` settings to all calls to `register_collection_catalog` (not just the first one).
- #143

use spatial_extent and datetime_extent everywhere

---

CHANGES.md
tests/test_factories.py
tipg/factory.py

This PR does:
- add `templated=True` for templated links 
- add `(Template URL)` in template URL title
- use `model_dump(exclude_none=True, mode="json")` instead of `mode=python` + deserialization

avoid serializing and deserializing when not necessary

---

tests/test_factories.py
tipg/dependencies.py
tipg/factory.py
tipg/model.py
tipg/templates/map.html

This PR does:
- replace maplibre with leaflet+protomaps-leaflet to support other TMS 
- deprecate non-tilematrixset prefixed endpoints for tiles/tilejson/stylejson/viewer to better match with the OGC Spec **breaking**
- re-order endpoints 
- remove **Z** limit to support negative values

(feature): new tile viewer supporting multiple TMS

---

docs/src/user_guide/endpoints.md

- Fix minor repetitive typo 'coma' and replace with 'comma'
- Went into my IDE and replace-all'd the 'Coma (,)' entries with 'Comma (,)'
- I guess just read and decide if it's correct now

Pull some of the endpoints out of their coma

---

CHANGES.md
pyproject.toml

FastAPI reverted their changed and now doesn't include *useless* dependencies https://github.com/fastapi/fastapi/discussions/11525 
we can move back to `fastapi` instead of `fastapi-slim` and also relaxe the version dependency!

revert to fastapi and update version

---

CHANGES.md
docs/src/user_guide/configuration.md
tipg/collections.py
tipg/settings.py

Column order is important for a few of the tables I work with and switching my users from their (database-defined) order to alphabetical caused a little shellshock. Essentially, getting this functionality will be the last part of our migration from a different feature server package.
We add an environment variable `TIPG_SORT_COLUMNS` (which defaults to `True`). Set it to `False` to disable sorting of columns. It's essentially trivial code, plus accompanying docs and `Settings` model updates.
Let me know if I need to add anything else here.

Added in environment variable for sorting/config

---

.pre-commit-config.yaml
CHANGES.md
pyproject.toml
tipg/collections.py
tipg/dependencies.py
tipg/factory.py
tipg/main.py
tipg/middleware.py
tipg/model.py

ref https://github.com/milesgranger/cramjam/issues/187

update starlette-cramjam and update ruff

---

CHANGES.md
tipg/collections.py

This PR fixes issues in the spatial filtering logic for tile generation, which were causing missing features when custom TMS are used.
When creating tiles with a custom TMS that has a different CRS (e.g. EPSG 2056), TiPG is constructing two different bounding boxes that aren’t in sync. One envelope is produced directly in the target CRS (e.g. 2056) while the other is produced in EPSG:4326 and then transformed into 2056. Because the transformation (and the segmentize step) may not be perfectly invertible, these two envelopes don’t match. As a result, only features that lie inside the intersection of both envelopes get selected. This effect is visible when zooming far enough into the dataset.
When using a custom TMS for EPSG 2056 data (in this example, contour lines), the following SQL …

Fix CRS Transformation for custom TMS

---

CHANGES.md
tests/routes/test_collections.py
tests/routes/test_non_geo.py
tipg/factory.py

```
curl --request GET http://127.0.0.1:8081/collections\?limit\=1 | jq '.collections[0].links'
[
{
"href": "http://127.0.0.1:8081/collections/public.my_data_geo",
"rel": "collection",
"type": "application/json"
},
{
"href": "http://127.0.0.1:8081/collections/public.my_data_geo/items",
"rel": "items",
"type": "application/geo+json"
},
{
"href": "http://127.0.0.1:8081/collections/public.my_data_geo/queryables",
"rel": "queryables",
"type": "application/schema+json"
},
{
"href": "http://127.0.0.1:8081/collections/public.my_data_geo/tiles",
"rel": "data",
"type": "application/json",
"title": "Collection TileSets"
},
{
"href": "http://127.0.0.1:8081/collections/public.my_data_geo/tiles/{tileMatrixSetId}",
"rel": "data",
"type": "application/json",
"templated": true,
"title": "Collection …
```

infer OGC Tiles links /collections and /collections/{collectionId} response

---

CHANGES.md
docs/src/advanced/customization.md
tests/conftest.py
tipg/collections.py
tipg/database.py
tipg/main.py
tipg/settings.py

overtake https://github.com/developmentseed/tipg/pull/191, https://github.com/developmentseed/tipg/pull/97

add the ability to use a schema other than pg_temp for installing catalog functions

---

CHANGES.md
dockerfiles/Dockerfile

Switching to official python base image over `bitnami` because of their changes in access

fix: switch to official python docker image over bitnami
